name: "ChromaDB Data Pipes 🖇️| Action"
description: "Import/Export data to/from ChromaDB and much more!"
inputs:
  pipeline:
    description: |
        The pipeline to run. Example:
        `cdp ds-get "hf://tazarov/chroma-qna?split=train" | cdp import "http://localhost:8000/default_database/chroma-qna" --upsert --create`
        Read more about pipelines: https://datapipes.chromadb.dev/
    required: true
    type: string
outputs:
  result:
    description: "Result of the action"
    value: ${{ steps.run.outputs.result }}

runs:
  using: docker
  image: docker://ghcr.io/amikos-tech/chromadb-data-pipes/cdp:latest
  args:
    - ${{ inputs.pipeline }}